### ISSUE TITLE
DefaultDomain from region.getOwners() does not hold names anymore

### ISSUE THREAD

**Issue by Blautee** [EngineHub/WorldGuardDocs#36]
Unlike stated in the documentaion, _region.getOwners()_ cannot be used to return playernames anymore. Instead the "ProfileCache" from _WorldGuard.getInstance().getProfileCache()_ can be used, which may should be reffered to in the corresponding documentation "protected-region.rst" :D

**Comment by Joo200** [comment]
That's not correct, you can still receive the player names from the DefaultDomain.

But by default WorldGuard saves the added players by the uuid to allow name changes.
There is already a warning in the docs for that:
![grafik](https://user-images.githubusercontent.com/15250323/174869723-9863da0b-db42-4025-9aaa-2f4b472cf8f3.png)

**Comment by Blautee** [comment]
Handling UUIDs indeed makes a lot of sense, but for my case I needed names. And the DefaultDomain for me did only return UUIDs and not names, thats why I got confused. It just looked like this:

**{players={uuids=[_uuid1_, _uuid2_], names=[]}, groups={names=[]}}**

But if it should return names, this is a problem with WorldGuard itself or my usage of it, and i will state my problem over there. Thanks for your help :D

**Comment by wizjany** [comment]
the names literally refer to offline player names which should not be depended on for anything. they are entirely separate from the uuids.
